CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    emailVerifiedAt TIMESTAMP NULL DEFAULT NULL,
    password VARCHAR(255) NOT NULL,
    age TINYINT UNSIGNED NOT NULL CHECK (age > 0 AND age <= 150),
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    rememberToken VARCHAR(255) NULL DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP NULL DEFAULT NULL,
    INDEX idx_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;